### ISSUE TITLE
Create a UI to force HTTPS if it's supported

### ISSUE THREAD

**Issue by kienstra** [xwp/pwa-wp#17]
**Please see the "Revised ACs" [comment](https://github.com/xwp/pwa-wp/issues/17#issuecomment-400434908) for the ACs, instead of this comment.**

Hi @westonruter and @postphotos,
What do you think about these ACs? Feel free to edit this.

**User Story: As a WordPress administrator, I want a UI to ensure that my site uses HTTPS if it's supported.**

- [x] AC1. Use the HTTPS detection logic from Issue #6
- [x] AC2. On the General Settings page, add a `<tr>` for HTTPS support (use JavaScript to move it after the home/site URLs)
- [x] AC3. If HTTPS is supported, but the WordPress Address (URL) and Site Address (URL) don't use HTTPS,  display this notice:
<img width="960" alt="possible-notice" src="https://user-images.githubusercontent.com/4063887/41925762-239456ce-7933-11e8-8148-d92331469d04.png">

- [x] AC4. On clicking "Click here," the WordPress Address (URL) and the Site Address (URL) change to HTTPS, and there's a redirect from HTTP to HTTPS
- [x] AC5. If HTTPS is not supported, display:
<img width="836" alt="not-supported" src="https://user-images.githubusercontent.com/4063887/41926060-db1e7392-7933-11e8-87a5-b28a4f86e351.png">

- [ ] AC6. Clicking "Recheck" triggers the loopback request from #6. Maybe there should be a notice at the top, like "HTTPS is still not supported" or "HTTP is supported."

- [x] AC7. If HTTPS is supported, and the WordPress Address (URL) and Site Address (URL) use HTTPS,  display:

<img width="1370" alt="https-supported" src="https://user-images.githubusercontent.com/4063887/41926277-766ceb58-7934-11e8-9153-b58dc36cc954.png">

- [ ] AC8. If HTTPS is enabled, show the user a toggle for HSTS (see issue #18).

- [x] AC9. Propose a UI and match the designs provided to meet WP core standards and look-and-feel, all to load on the general settings page.

**Comment by westonruter** [comment]
Instead of “click here” I think we should be using links with descriptive text like “re-check” or “set HTTPS”. Also, buttons may be more appropriate than links in some cases.

> AC6

Instead of “not supported” and “supported” I think it should be “Support detected” and “Support not detected”.

There should probably be some link off to somewhere to get more information about HTTPS if support is not detected.

> AC4

When support is detected, there should then be a checkbox presented to force the redirection from HTTP to HTTPS, in addition to changing the home/site URLs from HTTP to HTTPS. I think that this should be done without any page reloads because the user may have changed another setting on the page and it could be lost otherwise. So I think that clicking the “Check” button should do an Ajax request to check for support (even using the same request client-side that is being made via cron, which could have the added benefit of using the user's SSL certs). Then when that Ajax request returns affirmatively, then the table row with the checkbox could be shown. Upon clicking the checkbox, then JS can be used to update the home/site URL inputs to use HTTPS. Once the user then saves the changes, then the HTTPS redirection would be put in place at that point. Note that the user may end up getting prompted to re-login at this point if the admin also switched from HTTP to HTTPS.

**Comment by westonruter** [comment]
This is essentially implementing a UI for the constant described in [wp#28521](https://core.trac.wordpress.org/ticket/28521):

> As per [this post on make/core and its comments](https://make.wordpress.org/core/2014/06/11/ssl-taskforce/), we should introduce a new constant which becomes the iron-fisted ruler of HTTPS, imposing its might everywhere it can.

**Comment by kienstra** [comment]
**Revised ACs**

Hi @westonruter,
Thanks, you make some good points. How does this look? 

These ACs add your suggestions, though the AC numbers don't map to the previous ones.

AC1. Use the HTTPS detection logic from Issue #6
AC2. On the General Settings page, add a `<tr>` for HTTPS support to the bottom (there's no filter to add it higher on the page)
AC3. When support is detected, and the WordPress Address (URL) and Site Address (URL) also use HTTPS, display:
<img width="756" alt="https-support-detected-wordpress-address" src="https://user-images.githubusercontent.com/4063887/41934332-1607b050-794c-11e8-8c4f-01d61148bdfe.png">
AC4. When support is not detected, display:
<img width="795" alt="https-not-supported" src="https://user-images.githubusercontent.com/4063887/41934443-5723443c-794c-11e8-83eb-c443c9b74682.png">
AC5. Clicking "Re-check" triggers an AJAX request, not a page reload
AC6. If it then detects HTTPS support, and the WordPress Address (URL) and Site Address (URL) don't use HTTPS, display:
<img width="1114" alt="supports-https-not-using" src="https://user-images.githubusercontent.com/4063887/41934529-90df6d5e-794c-11e8-9df0-fcf00a1f2d8e.png">
AC7. This can also display on initially loading the General Settings page, if HTTPS is supported, but  the WordPress Address (URL) and Site Address (URL) don't use HTTPS
AC8. On clicking the checkbox, the WordPress Address (URL) and Site Address (URL) are changed from HTTPS to HTTP (even before clicking “Save Changes”)
AC9. On clicking "Save Changes," the setting to to redirect is saved, and the redirection is in effect

**Comment by kienstra** [comment]
Hi @westonruter,
Thanks for your responses.

>Use JavaScript to move it to the correct location,

Sounds good, I updated AC2 above.

>(AC3) Don't you mean when they are not using HTTPS?

I was thinking of when HTTPS is supported, and the home/site URLs also use HTTPS. In that case, there would be no need for a notice, or a checkbox to force HTTPS. Maybe there would be no need for an 'HTTPS Support' `<tr>` at all, though.

>(AC8) Changed via JavaScript in the input fields. No request is made to change the option in the background before clicking Save Changes. 

Thanks, I updated AC8 with that.

>Note, however, that a wp-config.php can define WP_SITEURL and WP_HOME constants which will override whatever you supply in the admin...

Thanks, I added that verbatim as AC10.

>If someone wants to turn off HTTPS support, for some reason, there should be a way to do that. So unchecking the checkbox can suspend the addition of the filter that forces the home/site URLs to be HTTPS.

Thanks, I added that verbatim as AC11.

**Comment by westonruter** [comment]
> I was thinking of when HTTPS is supported, and the home/site URLs also use HTTPS.

If the current site URL is HTTP, then the notice should be displayed for sure. If that's what you're saying then yes, agreed. If the site's URLs are currently HTTPS, then the notice maybe wouldn't need to be displayed except for being able to turn off HTTPS. So in that way, checking if `home` or `siteurl` don't start with `https://` then the notice table row should always be shown.

**Comment by kienstra** [comment]
Hi @westonruter, 
>If the current site URL is HTTP, then the notice should be displayed for sure.

Thanks, that's what I was thinking. 

>If the site's URLs are currently HTTPS, then the notice maybe wouldn't need to be displayed except for being able to turn off HTTPS.

That sounds good.

**Comment by postphotos** [comment]
Hi @westonruter, in #18 ([comment](https://github.com/xwp/pwa-wp/issues/18#issuecomment-400598807)) I described a scenario where caution should be placed in moving to full HSTS support. 

Perhaps somewhere in this dialogue a prompt to describe details (why their site isn't HTTPS/HSTS ready and what they can do to fix it) could be added?

I'd also recommend @jwold help design a userflow here as well to help make this a tad easier from a usability standpoint.

**Comment by kienstra** [comment]
**Design**

Thanks, @postphotos! If there are changes to the requirements here based on design work, it'd be good if they were soon. I might start developing for this soon.

**Comment by kienstra** [comment]
Update: waiting to develop for this, pending a design discussion on Monday.

**Comment by kevincoleman** [comment]
Would be great to also consider adding a help button/link for those who may want to learn what this does (linking out to a post or official docs).

**Comment by jwold** [comment]
We had a discussion earlier this week and went over the possible UI changes. 

Following is a sketch showing our work in progress for displaying the update notice. Feedback is welcome!

![updates page](https://user-images.githubusercontent.com/3411173/42399468-c37452ec-8122-11e8-99f4-9146fcbad0ce.png)

Additional things we could discuss further based on the notes above:

1. Welcome button - where would we want to put it, and what could it say?
2. Settings page for PWA - adding an indicator next to the check and re-check button.

**Comment by westonruter** [comment]
Instead of “images” it should probably just say “assets”, as the issue will be regarding media (images, videos, audio) and also scripts and stylesheets. Also, it should say “at least X issues” because we won't be able to maintain a comprehensive index of the entire site's URL space and the assets that get requested.

**Comment by kienstra** [comment]
**Possible UI**

Hi @jwold and @westonruter,
What do you think of this possible UI for "Settings" > "HTTPS Settings"? The dashboard widget above looks good, and could work along with this.

![possible-ui-https-settings](https://user-images.githubusercontent.com/4063887/42595584-5fec2868-8518-11e8-91ca-ea2b1c1a3c7c.png)

This is based on the [discovery document](https://docs.google.com/document/d/1hkyc-GEq60PXMI4wd7NNnNO3gu6aWhZK4HRsDlynH_I/edit?usp=sharing) and discussion from #17.

Thanks!

**Comment by jwold** [comment]
This is a great start on a UI and at a high level I think it works. 

1. When it says “you can block these below” what area below is it referring to? That’s not super clear. 

2. For the “upgrade all mixed content” and “HTTPS Support” checkboxes, are those both reversible options? For instance, if I checkmark them and save, and then come back later and uncheckmark. Is that a real life use case? I’m wondering if a radio button or a different type of button might make more sense here. 

3. Above the active mixed content and passive mixed content areas I wonder if we could have a headline. Something like… (and this is a bad example!) “It’s important for your site to support HTTPS because it’s super awesome and will change your life. Below are examples that could cause errors in your browser. 

4. The problem I’m struggling with when coming to this page is knowing what to take action on, it’s a lot to do. Now, if this page is intended for a developer, then maybe it’s fine! I’m thinking more the use case of a site owner without a lot of technical background.

**Comment by kienstra** [comment]
**Thanks, Great Points**

Hi @jwold,
Thanks a lot for your ideas.
1. That refers to the "Upgrade all mixed content" checkbox. You're right, the wording should be better in "you can block those..."
2. Good question about whether these are reversible.
* "upgrade all mixed content" is reversible
* "redirect from HTTP to HTTPS" could be reversible
* "Change the home/site URLS" is reversible, but on the "Settings" > "General Settings" page (it changes the value to HTTPS):
<img width="814" alt="site-url" src="https://user-images.githubusercontent.com/4063887/42603290-cd401450-8532-11e8-87ce-60c353847ff5.png">

3. Good to have a descriptive headline
4. Good point that it's not clear what to do. Maybe we could have a flow of actions based on the "Scan now" button:
* If there's no or only passive insecure content, a notice appears that recommends selecting "Change the home/site URLS..."
* If there's active insecure content, display the insecure URLs. And recommend looking at them more or using another plugin to fix them.
The display of URLs might be too much information for non-developers.

**Comment by westonruter** [comment]
Two more considerations:

* I wonder if during an initial install we can detect if HTTPS is available and set the proper URL when first setting up a site from scratch.
* We should show a warning on the dashboard if the site is not being served as HTTPS and direct the user to the settings screen for enabling it.

These could go into separate issues perhaps.

**Comment by kienstra** [comment]
**Initial install, warning in dashboard**

Hi @westonruter,
Good idea to have HTTPS detection on the initial install. And to have a warning on the dashboard to direct to this settings page.

**Comment by kienstra** [comment]
**New Proposed UIs**

Hi @jwold and @westonruter,
What do you think of this new UI? It might be part of an existing "Settings" page, as it doesn't have many options now.

This makes recommendations, where the previous UI I proposed was much more developer-oriented.

It uses a loopback request to the homepage (with HTTPS forced), and a match for insecure URLS (using output buffering). This would happen before the page loads, like the AMP validator does for the post editor.

Here are the settings pages, based on what kind of mixed content it finds. The first 3 screenshots are for when the HTTPS request succeeds, and the last is for when it fails.

![pwawp-17-no-insecure-content-jpg](https://user-images.githubusercontent.com/4063887/42710472-c908834a-86a9-11e8-9ed1-e2433549d36f.jpg)

![pwawp-17-only-passive-insecure-jepg](https://user-images.githubusercontent.com/4063887/42710762-07e21364-86ab-11e8-9766-8ff7f6a12a57.jpg)

![pwawp-17-active-and-passive-insecure-jpeg](https://user-images.githubusercontent.com/4063887/42710978-e2cd03da-86ab-11e8-9834-a4a49faf1303.jpg)

![pwawp-17-no-https-support-jpeg](https://user-images.githubusercontent.com/4063887/42711084-45b2bce2-86ac-11e8-81e1-8b5cc390c56f.jpg)

**Comment by jwold** [comment]
Great work Ryan! Got a few questions

https://v.usetapes.com/krqCZHieFT

**Comment by kienstra** [comment]
@jwold, thanks for your great points. I'm working on a response now.

**Comment by kienstra** [comment]
Hi @jwold,
Thanks for your great ideas. The numbers below are for the screenshot numbers above.

1. Selecting "Yes" in screenshot 1 above is reversible. How does this new screenshot look? It uses your idea of radio buttons, and also has different text.

![pwawp-17-https-settings-no-insecure-2-jpeg](https://user-images.githubusercontent.com/4063887/42717735-baca6dba-86c8-11e8-8259-f166d870487c.jpg)


2. Here's a similar change to the one above:

![pwawp-17-3-only-passive-jpeg](https://user-images.githubusercontent.com/4063887/42717681-519affb2-86c8-11e8-9206-78108828abf9.jpg)

3. The links for active and passive insecure content would simply go to the URL. For example:
```html
<a href="http://example.com/foo">http://example.com/foo</a>
```

If it's alright, I'll reply to you later about where the "More details" links go to

**Comment by kienstra** [comment]
**More Details Links**

Hi @jwold,
You had [asked](https://github.com/xwp/pwa-wp/issues/17#issuecomment-404950499) about where the "More details" links lead to.

3. Active and passive insecure content
This "More details" link might go [here](https://developer.mozilla.org/en-US/docs/Web/Security/Mixed_content/How_to_fix_website_with_mixed_content)
![pwawp-17-active-and-passive-insecure-jpeg](https://user-images.githubusercontent.com/4063887/42712977-54ba1aa8-86b3-11e8-904b-460c9cc579ca.jpg)

4. HTTPS request fails
This "More details" link would probably go to the page [HTTPS For WordPress](https://make.wordpress.org/support/user-manual/web-publishing/https-for-wordpress/)
![pwawp-17-no-https-support-jpeg](https://user-images.githubusercontent.com/4063887/42711084-45b2bce2-86ac-11e8-81e1-8b5cc390c56f.jpg)

**Comment by kienstra** [comment]
**Proposed UIs**

Here are the proposed UIs from above, but copied into this comment for simplicity.

Screenshots 1-3 are for when the HTTPS loopback succeeds, and 4 is for when it fails.

1. No insecure content

![pwawp-17-https-settings-no-insecure-2-jpeg](https://user-images.githubusercontent.com/4063887/42717735-baca6dba-86c8-11e8-8259-f166d870487c.jpg)


2. Only passive insecure content

![pwawp-17-3-only-passive-jpeg](https://user-images.githubusercontent.com/4063887/42717681-519affb2-86c8-11e8-9206-78108828abf9.jpg)

3. Active and passive insecure content
![pwawp-17-active-and-passive-insecure-jpeg](https://user-images.githubusercontent.com/4063887/42712977-54ba1aa8-86b3-11e8-904b-460c9cc579ca.jpg)

4. HTTPS request fails

![pwawp-17-no-https-support-jpeg](https://user-images.githubusercontent.com/4063887/42711084-45b2bce2-86ac-11e8-81e1-8b5cc390c56f.jpg)

**Comment by kienstra** [comment]
**Dashboard > WordPress Update**

Like @jwold [suggested](https://github.com/xwp/pwa-wp/issues/17#issuecomment-403142686), the UIs from the [comment above ](https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455) would probably go better in the Dashboard > WordPress Update section: 

![https-section](https://user-images.githubusercontent.com/4063887/43157056-773995ae-8f41-11e8-8053-f813c0ab7147.png)

**Comment by jwold** [comment]
Ryan,

Great thoughts and appreciate the diligence in putting together these UIs!

1. If we move the HTTPS section to Dashboard > WordPress then we might just want to add a red bubble to the sidebar when an upgrade is available. 

2. Suggested copy changes:

> HTTPS Upgrade > CHANGE TO > Enable HTTPS

> Your site looks to support HTTPS, but isn't using it. > CHANGE TO >  Your site appears to support HTTPS

> Upgrade Insecure URLS > CHANGE TO > Enable secure URLs

> Your home page didn't have any insecure URLS. Still, there might be other URLs on other pages that this would block. > CHANGE TO > Your home page doesn’t contain insecure URLs. However, there may be URLs on other pages that are blocked. More details. 

> There look to be issues with non-HTTPS URLs on your homepage. Please either address them, or upgrade them below. More details. > CHANGE TO > There appears to be issues with non-HTTPS URLs on your home page. Please resolve these or upgrade. More details. 

3. When you list out the URLs, perhaps having bullets on them would help? 

4. On this comment: https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455, you posted this screenshot: https://d.pr/i/4nvyM9, just want to validate that that check mark would be changed to a radio button. 

5. This is just an idea, so if we want to keep the "yes" and "no" radio buttons, I think that'd totally be fine. With that said, what if we explored a way to make the settings area look a bit more like Gutenberg? I like how the toggle works:

![toggle](https://user-images.githubusercontent.com/3411173/43159949-ab04193a-8f38-11e8-9755-21d5029c473f.jpeg)

**Comment by kienstra** [comment]
**Thanks!**

Hi @jwold,
Thanks a lot for your ideas.

1. Sounds good, a bubble would help when an update is available.
2. Good suggestions
>Your site looks to support HTTPS, but isn't using it. > CHANGE TO > Your site appears to support HTTPS

If we remove "but isn't using it," would it be clear enough that they aren't using it? Though the fact that this in on the "WordPress Updates" page might be enough.
3. Bullets would be good 😄 
4. Good catch. I meant for #3 in the [comment above](https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455) to have radio buttons, not a checkbox.
5. Good suggestion for Gutenberg-like toggles. I'll look at how we might use them here.

**Comment by jwold** [comment]
Spoke with @postphotos and @kienstra:

1. Suggest placing the UI for this on Settings > Reading
2. Put it at the bottom of that page with a headline, description line (HTTPS is essential to securing your WordPress site, we strongly suggest enabling HTTPS on your site), and then the conditional radio buttons discussed above. [Inspiration](https://d.pr/i/rFLjHv). If they DO have HTTPS just have a positive message indicating it.
3. Need to consider strings for polyglots for potential core merge proposal
4. In this [comment](https://github.com/xwp/pwa-wp/issues/17#issuecomment-407515503) we suggested a UI that is more similar to Gutenberg. It's instead suggested that we stick to a radio button style (for now) similar tot he settings page. 
5. Add inline re-check button, but we can start now without answering that. 

![checking](https://user-images.githubusercontent.com/3411173/43229387-756e5e66-9019-11e8-8979-93bf0a629a46.jpeg)


Additional notes:

- Note: If I've done things external of the WordPress site to enable HTTPS, I don't need these settings to help me, so the UI should take that into consideration. 
- How do we tell a site admin whether they're compatible or not using this tool? We could just show nothing, or we could have a re-check button. 
- What happens when a site is HTTPS compatible? It could show insecure content screenshot if it finds insecure URLs.

**Comment by kienstra** [comment]
@jwold, thanks a lot for your detailed notes.

**Comment by kienstra** [comment]
**Current Work In Progress**

Here's the current display from WIP PR #36:

<img width="1265" alt="reading-settings" src="https://user-images.githubusercontent.com/4063887/43243385-204b2970-906c-11e8-9f9b-14a4cbcb7d83.png">

The [design above](https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455) in screenshot #3 had listed all of the insecure URLs that it found, if there were both active and passive. This could do that also. But that seems really developer-oriented for the Reading Settings page.

**Comment by jwold** [comment]
> The design above in screenshot #3 had listed all of the insecure URLs that it found, if there were both active and passive. This could do that also. But that seems really developer-oriented for the Reading Settings page.


This isn't necessarily best practice, but what if we hid those urls in an expanding accordion link?

cc @postphotos

**Comment by kienstra** [comment]
Thanks, good idea to use an expanding accordion.

**Comment by westonruter** [comment]
@jwold Thoughts on why Reading Settings is the best place for the HTTPS settings? I think it makes more sense adjoined to the “WordPress Address (URL)” and “Site Address (URL)” settings on the General Settings screen since it is inherently tied to the URL, and enabling HTTPS will impact the URL.

**Comment by jwold** [comment]
@westonruter that was the initial thought I had, put it next to a place that affects the site URL. In chatting with Leo and Ryan we felt that Reading represented the viewing interaction that would happen with the site. For instance, we have “discourage search engines” there. Now that I say it that sounds a tad weak. 

@postphotos or @kienstra can you weigh in with what you were thinking as well?

**Comment by kienstra** [comment]
**Which Settings Page?**

Hi @jwold,
I thought that the "Reading Settings" page would be the best option, but still not a great one. The HTTPS section could be pretty big to add on the main "General Settings" page. 

Especially if we're listing the invalid URLs (see screenshot #3 [here](https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455)). Or if we have a [recheck button](https://github.com/xwp/pwa-wp/issues/17#issuecomment-407907140) with notices. 

But the context of the "General Settings" page probably matches HTTPS better than any other page.

**Comment by westonruter** [comment]
Can some of the elements be hidden behind an expandable container? I'm thinking that once you set HTTPS that usually you won't really need to change the settings again. Having an expandable section under the URL settings to reveal the HTTPS settings could be a good solution. If HTTPS is not enabled the section could be expanded since users need to really enable it more than ever. But once enabled the section could be collapsed, and once there are HTTPS issues discovered then there could be a red indication with a count for the number of issues which are revealed upon expansion.

**Comment by hellofromtonya** [comment]
Just my 2 cents, but my first thoughts were to have it on the "General Settings" too.  As @westonruter pointed out, the site's URLs are there.  You get a sense of whether you have HTTP or HTTPS by that screen. 

+1 for expandable container for all the extra details, such as a list of invalid URLs.  We may want to have a more intuitive UI within that container that provides more contextual information, such as what the list is, why it's there, and what to do to resolve each.

**Comment by postphotos** [comment]
Here are the UI/User flow notes from my call today with @jwold:  

1) We grouped the enable HTTPS and HSTS (see #18) toggles together, and grouped insecure content and its errors together.
2) We conditionally surfaced the errors (showing a few, as well as a count of how many) when the plugin finds them.

Questions that remain:
3) @kienstra, do we need to hide the insecure content fixes (Your "item 2" [here](https://github.com/xwp/pwa-wp/issues/17#issuecomment-406188455))?

![screenshot 2018-07-31 at 12 28 50 pm](https://user-images.githubusercontent.com/963672/43482518-c33b7db0-94bd-11e8-9a1a-c41f94e62afc.png)
![screenshot 2018-07-31 at 12 30 06 pm](https://user-images.githubusercontent.com/963672/43482516-c2fd7470-94bd-11e8-8561-03e7a8074f9e.png)
![screenshot 2018-07-31 at 12 29 55 pm](https://user-images.githubusercontent.com/963672/43482517-c31b02ba-94bd-11e8-9017-f88d208c0ff2.png)
![screenshot 2018-07-31 at 12 30 52 pm](https://user-images.githubusercontent.com/963672/43482515-c2dd0cb2-94bd-11e8-8185-2163d07fa5a9.png)

Let us know if there's enough fidelity here for you @kienstra. I'm also happy to work with you on the language here.

**Comment by kienstra** [comment]
Hi @postphotos,
Thanks a lot for your mockups.

What do you think of enabling HSTS automatically if the user has checked "HTTPS Upgrade" and "Upgrade Insecure URLs"? 

It looks like HSTS has a similar effect on insecure content as the [upgrade-insecure-requests](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#upgrading_insecure_requests) header (which checking "Upgrade Insecure URLs" adds). 

If a script hosted on the same domain has a HTTP URL, it forces it to HTTPS. Though [upgrade-insecure-requests](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#upgrading_insecure_requests) also applies to requests outside the domain.

HSTS can cause issues if the HTTPS request somehow fails. There's [no fallback](https://en.wikipedia.org/wiki/HTTP_Strict_Transport_Security#HSTS_mechanism_overview):

>If the security of the connection cannot be ensured (e.g. the server's TLS certificate is not trusted), show an error message and do not allow the user to access the web application.[12]

But this is something we'd probably have to handle even if the user checked an "HSTS" box, and HTTPS later failed. 

We might [do this](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Strict-Transport-Security):

>...setting the max-age to 0 (over a https connection) will immediately expire the Strict-Transport-Security header, allowing access via http.

**Comment by kienstra** [comment]
**Current UI From PR #36**

HTTPS supported, no insecure content:
<img width="1303" alt="https-supported-no-insecure-content" src="https://user-images.githubusercontent.com/4063887/43564484-95596c38-95ec-11e8-9103-f93b338e8eaa.png">

HTTPS supported, only passive insecure content
<img width="1302" alt="https-only-passive-insecure" src="https://user-images.githubusercontent.com/4063887/43564493-9da1aea0-95ec-11e8-9098-c3695f701e0d.png">

HTTPS supported, passive and active insecure content
<img width="1200" alt="passive-active-insecure-content" src="https://user-images.githubusercontent.com/4063887/43564519-b6416a5e-95ec-11e8-8dce-7349cb07972e.png">

**Comment by kienstra** [comment]
**Maybe Remove "Upgrade Insecure URLs" Checkbox**

Based on some feedback in the sync today, maybe we could remove the "Upgrade Insecure URLs" checkbox. And automatically [upgrade the insecure requests](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#upgrading_insecure_requests), only if there is active insecure content on the homepage.

Normally, the risk in [upgrading the insecure requests](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#upgrading_insecure_requests) is that when a HTTP URL is upgraded to HTTPS, the request could fail. And there's no fallback.

But if there are active insecure URLs, the browser already blocks them. So they're failing already, and upgrading them at least gives them a chance.

The main reason to have the checkbox, instead of upgrading all requests by default, is to prevent upgrading passive insecure URLs that might fail. 

For example, the `src` of an `<img>` is upgraded from HTTP to HTTPS, and fails. The image doesn't display, but it wouldn't have caused a browser error if it wasn't upgraded.

So this wouldn't [upgrade insecure requests](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/fixing-mixed-content#upgrading_insecure_requests) unless there's active insecure content.

This could still display the insecure URLs if there's active insecure content, like in screenshot 3 [above](https://github.com/xwp/pwa-wp/issues/17#issuecomment-4098121770).

**Comment by kienstra** [comment]
**Current UI For Active Insecure Content**

<img width="1429" alt="active-insecure-content" src="https://user-images.githubusercontent.com/4063887/43669266-60e41ad2-9747-11e8-96e3-a210ac5d058c.png">

**Comment by jwold** [comment]
@kienstra just synced with Leo and we propose the following updated UI. It removes sidebars and puts all list items in a bit of a box, with alternating row colors and a button to load more. Please let us know if any further questions. Thanks!

![img_e2ffbb83764e-1](https://user-images.githubusercontent.com/3411173/44058419-e8cbc2c0-9f02-11e8-9ca1-822e8676f5bd.jpeg)

**Comment by kienstra** [comment]
**Thanks For The UI Above**

Hi @jwold,
Thanks for the updated UI, and it was great to see you last week 😄 

1. How well do you think the blue/white row colors would fit in on the General Settings page? It looks like there isn't a pattern like this in any of the Core settings pages, and they're all relatively simple. But I'm not a designer 😄 

Here's the current UI:
<img width="1434" alt="scroll-through-insecure-urls" src="https://user-images.githubusercontent.com/4063887/44006465-854af292-9e4a-11e8-8a31-df089045e382.png">

2. Is the scrolling here enough? It's definitely possible to add the "Load more" button. 

But I don't think there will be more than 50 or 100 insecure URLs very often. It probably wouldn't be common to show those URLs at all. They're only shown if:
* The WordPress Address (URL) and Site Address (URL) are HTTP
* The site can support HTTPS (it has a certificate)
* There is active insecure content, like scripts or stylesheets. Not only images.

We've also been discussing the UI in #36.

3. Could you please elaborate on "removes sidebars"?

**Comment by postphotos** [comment]
Just had a mini-workshop w/ @kienstra. 

1) We toned down the striping to look a tad different to match the general settings page look-and-feel. We tried to eliminate the need for a second overflow/scroll on the page (and avoid using an unnecessary AJAX request) and have done so by changing my sketch with @jwold from earlier in the day.

Here's what we came up with:
<img width="1031" alt="leo-screenshot" src="https://user-images.githubusercontent.com/963672/44072685-f50d974a-9f55-11e8-898c-881eaa8888bc.png">

We also moved the number count out of the copy button and into the overflow button.

2) We discussed this and think it might not be as friendly copy. We've revised this to be: `We found content on your site that wasn’t loading correctly over HTTPS. While we will try to fix these links automatically, but you might check to be sure your pages work as expected.`

At this point, pending code review for #36, I feel this issue is soon ready for close. Thanks for all the hard work, folks! 🎉

**Comment by kienstra** [comment]
Great ideas on the design here, @postphotos! This looks really good.

**Comment by kienstra** [comment]
Thanks to Leo's design above, and some style rules he added, here's the current UI as applied in #36:

<img width="1373" alt="current-state" src="https://user-images.githubusercontent.com/4063887/44074133-09dcb5dc-9f5d-11e8-8d0b-4d29aef09a4c.png">

**Comment by jwold** [comment]
Really happy with where this landed! A few thoughts:

1. Adding padding to top and bottom of the urls (2-4 pixels top and bottom) could make it feel a little less cramped. 
2. Love the button change showing the number of urls available. Great job. 
3. What happens when a url is too long, will it just cut off? If so that should be fine. An ellipse could be useful. 
4. No border around the whole thing actually seems to make sense here. 
5. Minor point, what if we did a border-left of 3-5 pixels to indent the entire thing. Curious what @postphotos thinks.

**Comment by kienstra** [comment]
**Thanks**
*Screenshots Applying Suggestions*

Hi @jwold,
Thanks for your great suggestions.

Here are what your points 1. and 5. look like. Of course, this would be easy to change pending your suggestions:

<img width="1216" alt="styling-ui" src="https://user-images.githubusercontent.com/4063887/44132619-71c15e00-a020-11e8-8814-1ca8da823627.png">

3. The URLs are truncated, with an ellipsis if they're too long:
<img width="1372" alt="truncated-ellipsis" src="https://user-images.githubusercontent.com/4063887/44133195-1bb1da54-a024-11e8-8659-9cedbb42f73e.png">

**Comment by kienstra** [comment]
**Show more button**

Hi @ThierryA,
Thanks for suggesting the "Show more" button. It's now applied with https://github.com/xwp/pwa-wp/pull/36/commits/98d3e27e247bc7a2f69ab51c8a1937333a2e7254:

<img width="1392" alt="more-button" src="https://user-images.githubusercontent.com/4063887/44225072-02226980-a152-11e8-8721-c9d68f2a6eea.png">

**Comment by kienstra** [comment]
**Copy Changes**

Hi @westonruter,
Here are some copy changes, including your suggestion of using 'Upgrade to secure connection' instead of 'HTTPS Upgrade' (applied in https://github.com/xwp/pwa-wp/pull/36/commits/199f146b5af739ba7a1fe40c58c879b2eca689a7):

<img width="1395" alt="copy-changes" src="https://user-images.githubusercontent.com/4063887/44225676-b83a8300-a153-11e8-940b-45873f6c0ddb.png">

**Comment by kienstra** [comment]
**Passive Mixed Content: Handle This Also**

As @amedina mentioned, [passive mixed content](https://developers.google.com/web/fundamentals/security/prevent-mixed-content/what-is-mixed-content#passive_mixed_content) like HTTP images are an issue with service workers ([reference](https://github.com/w3c/ServiceWorker/issues/813#issuecomment-366941915)).

The blocker to this before was that there's no fallback if the upgraded URL fails. For example, if an image at http://example.com/foo.jpeg is upgraded to HTTPS and fails.

But @westonruter had a good idea of making requests for all insecure content, at the upgraded HTTPS URL, to ensure the requests don't fail.
