### ISSUE TITLE
Roadmap for new features

### ISSUE THREAD

**Issue by yogeshbeniwal** [xwp/pwa-wp#564]
Starting this thread to have a conversation about features which may/should be implemented in this plugin. Considering to keep it as a running list of features:

As per https://amp.dev/documentation/guides-and-tutorials/learn/combine-amp-pwa/

- [ ] AMP pages with PWA features
- [ ] AMP as entry point into PWA
- [ ] Use AMP as data source

**Comment by westonruter** [comment]
Thanks, but AMP is out of scope for this plugin.
