### ISSUE TITLE
CDS 18: Extend `twentyseventeen` to a showcase of PWA + AMP

### ISSUE THREAD

**Issue by postphotos** [xwp/pwa-wp#90]
As a site owner building a WordPress site, I should have a `twentyseventeen` child theme that not only looks polished and modern, but also includes PWA and AMP supports to showcase the modern web technologies of the `PWA` and `AMP` plugins.

Replaces #88. _To be based on (and work to be conducted in) @westonruter's [child theme](https://github.com/westonruter/twentyseventeen-westonson), `westonson`._
 
- [ ] AC1: This child theme needs to be Native AMP by default, and surface no errors in the AMP compatibility tool on activation. (_Work on this AC will be done in_  [twentyseventeen-westonson repo Issue 3](https://github.com/westonruter/twentyseventeen-westonson/issues/3))
- [ ] AC2: This child theme should use streaming for loading "heavy" content and work without errors or performance issues.   (_Work on this AC will be done in_  [twentyseventeen-westonson repo Issue 6](https://github.com/westonruter/twentyseventeen-westonson/issues/6))
- [ ] AC3: Offline commenting, leveraging `<amp-live-list>` from the AMP Plugin (and the efforts in #87), should not only be enabled by default but also report no errors in the AMP compatibility tool. (_Work on this AC will be done in both_ #87 _**Offline Commenting** and in_  [twentyseventeen-westonson repo Issue 3](https://github.com/westonruter/twentyseventeen-westonson/issues/3))
- [ ] AC4: Optimized offline page - come up with animations that work well for a `500` page. Inspiration should be taken from something like [Github](https://github.com/500). Other inspirations could come from [404 pages](https://colorlib.com/wp/free-error-page-templates/) as well. (A custom `404` page wouldn't be a bad idea, too, but is not a requirement.) (_Work on this AC will be done in_ [twentyseventeen-westonson repo Issue 4](https://github.com/westonruter/twentyseventeen-westonson/issues/4))

**Demo site**
- [ ] AC5: This child theme should extend the existing designs of `twentyseventeen` and enhance the user experience though a clean, elegant and playful design. While some efforts would be in the `westonson` theme itself, some of this would be shown on a demo site with these customizations.
- [ ] AC6: This demo site should, of course, showcase AC1-AC4 above.
- [ ] AC7: List out what features showcase PWA, AMP and other bells and whistles that make this work interesting. (Related: #68.) This could also be in the form of a blog post describing how we built what we built.

AC2, AC4, AC5 and AC6 will likely be broken into new tickets for design, FE and BE efforts.

**Comment by westonruter** [comment]
I think the offline page could also be used to list out the URLs that have been cached for offline access. That would be helpful for the user.

**Comment by westonruter** [comment]
@jwold  The video should only be like 15-30 seconds. Very short. Just long enough to show the header animate when navigating from homepage to interior page, and to show the (complex embedded) content dynamically changing as navigating but the header staying fixed. Maybe a good approach would be to do it in a loop where the user starts at the homepage then navigates to three of the nav menu items and then goea back to the homepage. That could then loop indefinitely in a seamless way, and I could speak over it without worrying about timing. So it could be even just 7 seconds looping even.
